import { generateSlide } from "@/lib/generate-slide";

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();
    const res = await generateSlide(prompt);
    // Return text response immediately. Images will be generated by the client.
    return Response.json(res);
  } catch (e) {
    console.error(e);
    return Response.json(
      { error: "Failed to generate slides" },
      { status: 500 },
    );
  }
}
